Extend validation pipeline with OTEL validation

diff --git a/.pipelines/azure_pipeline_validation_appmonitoring.yaml b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
--- a/.pipelines/azure_pipeline_validation_appmonitoring.yaml
+++ b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
@@ -30,7 +30,8 @@ variables:
   dotnetTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-dotnet-app:latest'
   dotnetTestAppName: 'dotnet-test-app'
   testNamespace: 'test-ns'
-  aiResourceId: '/subscriptions/5a3b3ba4-3a42-42ae-b2cb-f882345803bc/resourceGroups/aks-appmonitoring-pipeline/providers/microsoft.insights/components/appmonitoring-pipeline-validation-ai'
+  aiResourceId: '/subscriptions/5a3b3ba4-3a42-42ae-b2cb-f882345803bc/resourcegroups/aks-appmonitoring-pipeline/providers/microsoft.insights/components/appmonitoring-pipeline-validation-ai-otel'
+  lawResourceId: '/subscriptions/5a3b3ba4-3a42-42ae-b2cb-f882345803bc/resourcegroups/ai_appmonitoring-pipeline-validation-ai-ote_37743a46-5226-447c-842b-35fac54dbd92_managed/providers/microsoft.operationalinsights/workspaces/managed-appmonitoring-pipeline-validation-ai-otel-ws'
   Codeql.Enabled: true
   Codeql.BuildIdentifier: 'linuxbuild'
   AKSResourceGroup: 'aks-appmonitoring-pipeline'
@@ -349,13 +350,33 @@ jobs:
         export PYTHON_TEST_APP_NAME="${{ variables.pythonTestAppName }}"
         export DOTNET_TEST_APP_NAME="${{ variables.dotnetTestAppName }}"
 
-        echo "Wait 30s for telemetry to flow..."
-        sleep 30
-        
         sudo chmod u+x ./validate_ai.sh
 
         if ! ./validate_ai.sh ${{ variables.aiResourceId }} ${{ variables.testNamespace }}; then
           echo "AI telemetry validation failed"
+          exit 1
+        fi
+
+  - task: AzureCLI@2
+    displayName: "Check test apps are sending OTEL logs and traces to LAW"
+    inputs:
+      azureSubscription: ${{ variables.armServiceConnectionName }}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        cd appmonitoring/scripts
+        pwd
+        az account set --subscription ${{ variables.subscription }}
+        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 
+        export JAVA_TEST_APP_NAME="${{ variables.javaTestAppName }}"
+        export NODEJS_TEST_APP_NAME="${{ variables.nodeTestAppName }}"
+        export PYTHON_TEST_APP_NAME="${{ variables.pythonTestAppName }}"
+        export DOTNET_TEST_APP_NAME="${{ variables.dotnetTestAppName }}"
+
+        sudo chmod u+x ./validate_otel.sh
+
+        if ! ./validate_otel.sh ${{ variables.lawResourceId }} ${{ variables.testNamespace }}; then
+          echo "OTEL telemetry validation failed"
           exit 1
         fi
 
