fix: update helm install process by removing dry run and debug steps in clean-install-appmonitoring-oci.sh

diff --git a/.pipelines/azure_pipeline_validation_appmonitoring.yaml b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
--- a/.pipelines/azure_pipeline_validation_appmonitoring.yaml
+++ b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
@@ -22,8 +22,8 @@ variables:
   repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/aidev'
   repoTestImageRelativePath: 'test/azuremonitor/applicationinsights/aidev'
   repoTestImageName: '${{ variables.containerRegistry }}.azurecr.io/${{ variables.repoTestImageRelativePath }}'
-  repoTestExtensionPath: '${{ variables.containerRegistry }}.azurecr.io/test/azuremonitor/applicationinsights/helm'
-  repoExtensionPath: '${{ variables.containerRegistry }}.azurecr.io/azuremonitor/applicationinsights/helm'
+  repoTestExtensionPath: '${{ variables.containerRegistry }}.azurecr.io/test/azuremonitor/applicationinsights/helm/'
+  repoExtensionPath: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/helm/dev'
   javaTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-java-app:latest'
   javaTestAppName: 'java-test-app'
   nodeTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-nodejs-app:latest'
@@ -104,6 +104,7 @@ jobs:
     devOciTagSufix: $(imageTag)-rc.$(Build.BuildId)
     testImageName: ${{ variables.repoTestImageName }}:${{ variables.testImageTagSuffix }}
     fullImageName: ${{ variables.repoImageName }}:${{ variables.prodImageTagSuffix }}
+    fullOciImageName: ${{ variables.repoExtensionPath }}:$(devOciTagSufix)
     # This is necessary because of: https://github.com/moby/moby/issues/37965
     DOCKER_BUILDKIT: 1
 
@@ -493,9 +494,22 @@ jobs:
           exit 1
         fi
         
+        echo "Retagging and renaming OCI chart from test to production path..."
+        testChartPath="${{ variables.repoTestExtensionPath }}/app-monitoring-extension:$(devOciTagSufix)"
+        prodChartPath="${{ variables.repoExtensionPath }}:$(prodImageTagSuffix)"
+        
+        echo "Copying chart from ${testChartPath} to ${prodChartPath}..."
+        az acr import --name ${{ variables.containerRegistry }} --source ${testChartPath} --image ${prodChartPath} --resource-group ${{ variables.containerRegistryResourceGroup }}
+        if [ $? -ne 0 ]; then
+          echo "##vso[task.logissue type=error]az acr import for OCI chart failed."
+          exit 1
+        fi
+        
         mkdir -p $(Build.ArtifactStagingDirectory)/linux
-        echo "Setting the image name..."
+        echo "Setting the image name to $(fullImageName)"
         echo $(fullImageName) > $(Build.ArtifactStagingDirectory)/linux/fullImageName.txt
+        echo "Setting the oci image name to $(fullOciImageName)"
+        echo $(fullOciImageName) > $(Build.ArtifactStagingDirectory)/linux/fullOciImageName.txt
 
   - task: PublishBuildArtifacts@1
     inputs:
