add changes

diff --git a/.pipelines/azure_pipeline_validation_appmonitoring.yaml b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
--- a/.pipelines/azure_pipeline_validation_appmonitoring.yaml
+++ b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
@@ -302,7 +302,7 @@ jobs:
         fi
 
   - task: AzureCLI@2
-    displayName: "Validate Test apps are re-mutated and sending telemetry"
+    displayName: "Restart test Apps"
     inputs:
       azureSubscription: ${{ variables.armServiceConnectionName }}
       scriptType: bash
@@ -312,18 +312,41 @@ jobs:
         pwd
         az account set --subscription ${{ variables.subscription }}
         az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 
-        export JAVA_TEST_IMAGE_NAME=${{ variables.javaTestAppImageName }}
-        export NODEJS_TEST_IMAGE_NAME=${{ variables.nodeTestAppImageName }}
-        export TEST_NS="${{ variables.testNamespace }}"
-        export JAVA_TEST_APP_NAME="${{ variables.javaTestAppName }}-new"
-        export NODEJS_TEST_APP_NAME="${{ variables.nodeTestAppName }}-new"
-        
-        sudo chmod +x ../scripts/install-test-apps.sh
 
-        if ! ../scripts/install-test-apps.sh; then
-          echo "Test apps installation failed"
+        kubectl rollout restart deployment/$webhook_deployment -n ${{ variables.testNamespace }}
+
+  - task: AzureCLI@2
+    displayName: "Check test apps were mutated correctly"
+    inputs:
+      azureSubscription: ${{ variables.armServiceConnectionName }}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        cd appmonitoring/scripts
+        pwd
+        az account set --subscription ${{ variables.subscription }}
+        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }}
+        
+        sudo chmod u+x ./validate-mutation.sh
+
+        if ! ./validate-mutation.sh "test-app-java" "test-app-nodejs" "test-ns"; then
+          echo "Mutation validation failed"
           exit 1
         fi
+
+  - task: AzureCLI@2
+    displayName: "Check test apps are sending telemetry to AI"
+    inputs:
+      azureSubscription: ${{ variables.armServiceConnectionName }}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        cd appmonitoring/scripts
+        pwd
+        az account set --subscription ${{ variables.subscription }}
+        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 
+        export JAVA_TEST_APP_NAME="${{ variables.javaTestAppName }}"
+        export NODEJS_TEST_APP_NAME="${{ variables.nodeTestAppName }}"
 
         echo "Wait for 3m for telemetry to flow..."
         sleep 180
@@ -334,7 +357,7 @@ jobs:
           echo "AI telemetry validation failed"
           exit 1
         fi
-
+        
   - task: AzureCLI@2
     displayName: "Retag the image as ready to deploy"
     inputs:
