Refactor pipeline variables and add steps for OCI extension chart preparation and publishing

diff --git a/.pipelines/azure_pipeline_validation_appmonitoring.yaml b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
--- a/.pipelines/azure_pipeline_validation_appmonitoring.yaml
+++ b/.pipelines/azure_pipeline_validation_appmonitoring.yaml
@@ -20,7 +20,11 @@ variables:
   containerRegistry: 'appmonitoring' # this build pushes to aicommon.azurecr.io with an image that is used for testing in validation cluster, then pushes an image once tests pass. That image is latre picked up by the release pipeline and reuploaded to MCR
   containerRegistryResourceGroup: 'aks-appmonitoring-container-registry'
   repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/aidev'
-  repoTestImageName: '${{ variables.containerRegistry }}.azurecr.io/test/azuremonitor/applicationinsights/aidev'
+  repoTestImageRelativePath: 'test/azuremonitor/applicationinsights/aidev'
+  repoTestImageName: '${{ variables.containerRegistry }}.azurecr.io/${{ variables.repoTestImageRelativePath }}'
+  repoTestExtensionPath: '${{ variables.containerRegistry }}.azurecr.io/test/azuremonitor/applicationinsights/helm'
+  repoExtensionRelativePath: 'public/azuremonitor/applicationinsights/helm/extension-dev'
+  repoExtensionPath: '${{ variables.containerRegistry }}.azurecr.io/${{ variables.repoExtensionRelativePath }}'
   javaTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-java-app:latest'
   javaTestAppName: 'java-test-app'
   nodeTestAppImageName: '${{ variables.containerRegistry }}.azurecr.io/demoaks-nodejs-app:latest'
@@ -99,9 +103,13 @@ jobs:
     name: rambhatt-test-es-pool
   variables:
     imageTag: $[ dependencies.common.outputs['setup.imageTag'] ]
+    finalProdImageTag: $[ dependencies.common.outputs['setup.imageTag'] ]
     testImageTagSuffix: $(imageTag)-$(Build.BuildId)
+    prodImageTagSuffix: $(imageTag)-rc.$(Build.BuildId)
+    devOciTagSufix: $(imageTag)-rc.$(Build.BuildId)
     testImageName: ${{ variables.repoTestImageName }}:${{ variables.testImageTagSuffix }}
-    fullImageName: ${{ variables.repoImageName }}:$(imageTag)-rc.$(Build.BuildId)
+    fullImageName: ${{ variables.repoImageName }}:${{ variables.prodImageTagSuffix }}
+    fullOciImageName: ${{ variables.repoExtensionPath }}:$(devOciTagSufix)
     # This is necessary because of: https://github.com/moby/moby/issues/37965
     DOCKER_BUILDKIT: 1
 
@@ -208,23 +216,65 @@ jobs:
   - bash: |
         echo "##vso[task.setvariable variable=testImageName;isOutput=true]$(testImageName)"
         echo "##vso[task.setvariable variable=fullImageName;isOutput=true]$(fullImageName)"
+        echo "##vso[task.setvariable variable=fullOciImageName;isOutput=true]$(fullOciImageName)"
         echo "##vso[task.setvariable variable=testImageTagSuffix;isOutput=true]$(testImageTagSuffix)"
+        echo "##vso[task.setvariable variable=prodImageTagSuffix;isOutput=true]$(prodImageTagSuffix)"
+        echo "##vso[task.setvariable variable=devOciTagSufix;isOutput=true]$(devOciTagSufix)"
+        echo "##vso[task.setvariable variable=finalProdImageTag;isOutput=true]$(finalProdImageTag)"
     name: exportVars
 
 
 - job: validate_webhook_image
   dependsOn: build_linux
-  condition: and(succeeded(), eq(variables['IS_PR'], 'False'))
+  # condition: and(succeeded(), eq(variables['IS_PR'], 'False'))
   pool:
     name: rambhatt-test-es-pool
   variables:
     testImageName:  $[ dependencies.build_linux.outputs['exportVars.testImageName'] ]
     fullImageName:  $[ dependencies.build_linux.outputs['exportVars.fullImageName'] ]
+    fullOciImageName:  $[ dependencies.build_linux.outputs['exportVars.fullOciImageName'] ]
     testImageTagSuffix: $[ dependencies.build_linux.outputs['exportVars.testImageTagSuffix'] ]
+    prodImageTagSuffix: $[ dependencies.build_linux.outputs['exportVars.prodImageTagSuffix'] ]
+    devOciTagSufix: $[ dependencies.build_linux.outputs['exportVars.devOciTagSufix'] ]
+    finalProdImageTag: $[ dependencies.build_linux.outputs['exportVars.finalProdImageTag'] ]
     # This is necessary because of: https://github.com/moby/moby/issues/37965
     DOCKER_BUILDKIT: 1
 
   steps:
+  - task: AzureCLI@2
+    displayName: "Prepare and Push Extension charts as OCI"
+    inputs:
+      azureSubscription: ${{ variables.armServiceConnectionName }}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        cd appmonitoring/scripts
+        pwd
+        az account set --subscription ${{ variables.subscription }}
+        az aks get-credentials --resource-group ${{ variables.AKSResourceGroup }} --name ${{ variables.AKSResourceName }} 
+
+        sudo chmod u+x ./prepare-extension-charts.sh
+
+        echo "Preparing extension charts (replacing placeholders with runtime values)..."
+        if ! ./prepare-extension-charts.sh ../app-monitoring-extension $(finalProdImageTag) $(devOciTagSufix); then
+          echo "Chart preparation failed"
+          exit 1
+        fi
+
+        echo "Packaging modified chart..."
+        cd ..
+        helm package app-monitoring-extension
+        
+        echo "Copying packaged chart to artifact staging directory..."
+        mkdir -p $(Build.ArtifactStagingDirectory)/charts
+        cp app-monitoring-extension-*.tgz $(Build.ArtifactStagingDirectory)/charts/
+        
+        echo "Logging into ACR..."
+        az acr login -n ${{ variables.containerRegistry }}
+
+        echo "Pushing modified chart to OCI registry..."
+        helm push app-monitoring-extension-$(devOciTagSufix).tgz oci://${{ variables.repoTestExtensionPath }}
+
   - task: AzureCLI@2
     displayName: "Create deployment in AKS"
     inputs:
@@ -432,6 +482,24 @@ jobs:
         kubectl describe deployment app-monitoring-webhook -n kube-system
         kubectl get pods -n kube-system -l app=app-monitoring-webhook -o wide
         echo "Webhook deployment is healthy again, took ${rollout_duration_ms} milliseconds to restart."
+
+- job: retag_and_publish_image
+  displayName: "Retag and Publish Image"
+  dependsOn: 
+    - build_linux
+    - validate_webhook_image
+  condition: and(succeeded(), eq(variables['IS_PR'], 'False'))
+  pool:
+    name: rambhatt-test-es-pool
+  variables:
+    testImageName: $[ dependencies.build_linux.outputs['exportVars.testImageName'] ]
+    fullImageName: $[ dependencies.build_linux.outputs['exportVars.fullImageName'] ]
+    testImageTagSuffix: $[ dependencies.build_linux.outputs['exportVars.testImageTagSuffix'] ]
+
+  steps:
+  - checkout: self
+    fetchDepth: 0
+    fetchTags: true
 
   - task: AzureCLI@2
     displayName: "Retag the image as ready to deploy"
